pipeline {
    agent any

    stages {

        stage('Clone') {
            steps {
                git 'https://github.com/KETAVATHDILESWAR/flask-cicd.git'
            }
        }

        stage('Install') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip install -r requirements.txt
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                echo "Running Tests"
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                pkill -f app.py || true
                nohup python3 app.py &
                '''
            }
        }
    }
}
